In [2]:
import torch

In [ ]:

m = torch.Tensor([1, 2, 3])
n = torch.Tensor([[4],
                 [5]])
m,n

(tensor([1., 2., 3.]),
 tensor([[4.],
         [5.]]))

In [41]:
# 
result1 = m -n
result2 = torch.sub(m, n)

result1, result2

(tensor([[-3., -2., -1.],
         [-4., -3., -2.]]),
 tensor([[-3., -2., -1.],
         [-4., -3., -2.]]))

In [42]:
# 使用原地相减的方法
result3 = m.sub_(n)
result3
# 把 m - n 的结果写回 m，但 m 只有 [1, 3] 的空间，而 m - n 需要 [2, 3]，无法原地存储，所以 PyTorch 拒绝执行

RuntimeError: output with shape [3] doesn't match the broadcast shape [2, 3]

In [3]:
# 创建[3, 2] [4, 2]的随机数矩阵PQ
P = torch.normal(0,0.01,(3, 2))
Q = torch.normal(0,0.01,(4, 2))
P, Q

(tensor([[ 0.0057, -0.0092],
         [ 0.0094,  0.0108],
         [ 0.0098,  0.0096]]),
 tensor([[-0.0031,  0.0051],
         [ 0.0054,  0.0101],
         [-0.0033,  0.0057],
         [ 0.0002,  0.0042]]))

In [5]:
# 对Q进行形状变换得到的Q的转置

Q_transposed = Q.t()

Q_transposed

tensor([[-0.0031,  0.0054, -0.0033,  0.0002],
        [ 0.0051,  0.0101,  0.0057,  0.0042]])

In [6]:
# 对上述得到的P和Qt求内积
inner_product = torch.dot(P, Q_transposed)
inner_product
# 两个矩阵大小不匹配，无法进行内积计算，可能要表达的是矩阵相乘？？

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [ ]:
# 进行矩阵相乘
inner_product = torch.mm(P, Q_transposed)
inner_product

tensor([[-6.3262e-06, -1.2324e-06,  1.5529e-06, -4.6522e-06],
        [ 1.1925e-04,  1.3513e-05,  8.4508e-06,  2.0049e-04],
        [-2.0220e-06, -8.0271e-06,  3.0124e-05,  8.7098e-05]])

In [52]:
# 第三问
x = torch.tensor(1.0,requires_grad=True,dtype=torch.float32)
y1 = x**2
with torch.no_grad(): # 按要求这一步计算不计算梯度
    y2 = x**3
y3 = y1 + y2

y3.backward() # 反向传播求梯度
print(f'x = {x}, y3 = {y3}, y1 = {y1}, y2 = {y2},dy3/dx = {x.grad}')

x = 1.0, y3 = 2.0, y1 = 1.0, y2 = 1.0,dy3/dx = 2.0
